LOG_CHECKIN_ADD 	= "Checkin Add"
LOG_CHECKIN_OPEN 	= "Checkin Open"
LOG_CHECKIN_CLOSE 	= "Checkin Close"
LOG_CHECKIN_COLLECT_ADD	= "Checkin Collect Add"
LOG_CHECKIN_COLLECT_REMOVE = "Checkin Collect Remove"
LOG_CHECKIN_LIKE 	= "Checkin Like"
LOG_CHECKIN_UNLIKE 	= "Checkin Unlike"
LOG_CHECKIN_COMMENT	= "Checkin Comment"
LOG_CHECKIN_LOCATE 	= "Checkin Locate"
LOG_CHECKIN_NAVIGATE = "Checkin Navigate"

LOG_TOGO_OPEN 		= "Togo Open"
LOG_TOGO_CLOSE 		= "Togo Close"
LOG_TOGO_ADD 		= "Togo Add"
LOG_TOGO_REMOVE 		= "Togo Remove"
LOG_TOGO_LOCATE 	= "Togo Locate"
LOG_TOGO_NAVIGATE 	= "Togo Navigate"
LOG_REPORT_CHECKIN 	= "Report Checkin"
LOG_REPORT_TOGO		= "Report Togo"
LOG_REPORT_ANYWHERE 	= "Report Anywhere"
LOG_SUMMARY			= "Summary"
LOG_NEWS_CLICKED_HOT_CHECKIN = "News Clicked Hot Checkin"
LOG_NEWS_CLICKED_HOT_SPOT	= "News Clicked Hot Spot"
LOG_NEWS_CLICKED_LIKE 		= "News Clicked Like"
LOG_NEWS_CLICKED_COMMENT		= "News Clicked Comment"
LOG_NEWS_CLICKED_COLLECT		= "News Clicked Collect"
LOG_NOTIFICATION_CLICKED_HOT_CHECKIN = "Notification Clicked Hot Checkin"
LOG_NOTIFICATION_CLICKED_HOT_SPOT	= "Notification Clicked Hot Spot"
LOG_NOTIFICATION_CLICKED_LIKE 		= "Notification Clicked Like"
LOG_NOTIFICATION_CLICKED_COMMENT		= "Notification Clicked Comment"
LOG_NOTIFICATION_REMOVE_HOT_CHECKIN 	= "Notification Remove Hot Checkin"
LOG_NOTIFICATION_REMOVE_HOT_SPOT		= "Notification Remove Hot Spot"
LOG_NOTIFICATION_REMOVE_LIKE 		= "Notification Remove Like"
LOG_NOTIFICATION_REMOVE_COMMENT		= "Notification Remove Comment"
LOG_SEARCH_LOCATION = "Search Location"

LOG_NOTE_IS_SELF_CHECKIN = " Is Self Checkin"
LOG_NOTE_IS_NOT_SELF_CHECKIN = " Is Not Self Checkin"
LOG_NOTE_IS_COLLECTED_CHECKIN = " Is Collected Checkin"
LOG_NOTE_IS_OTHER_CHECKIN = " Is Other Checkin"

LOG_NOTE_IS_COLLECTED_TOGO = " Is Collected Togo"
LOG_NOTE_IS_NOT_COLLECTED_TOGO = " Is Not Collected Togo"

LOG_NOTIFICATION_HOT_CHECKIN 	= "Notification Hot Checkin"
LOG_NOTIFICATION_HOT_SPOT		= "Notification Hot Spot"
LOG_NOTIFICATION_LIKE 		= "Notification Like"
LOG_NOTIFICATION_COMMENT		= "Notification Comment"
